# Generated by Django 3.0.4 on 2020-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetvalue',
            name='currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AlterField(
            model_name='assetvalue',
            name='settlement_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
