# Generated by Django 3.0.4 on 2020-03-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200322_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetvalue',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.Asset'),
        ),
    ]
